### ISSUE TITLE
Problem with Gitea makefile

### ISSUE THREAD

**Issue by lauriejh** [LCBC-UiO/tuls#5]
Hi Florian/others,

I was following the quick start guide to install on our Linux VM and ran into this:

![image](https://user-images.githubusercontent.com/36158703/185900596-405ea13f-69bd-4d12-a89f-353cf7ae5fec.png)

I can see that the Gitea makefile was updated in a recent commit; just wondering if you can see what the issue is here?

Also (sorry, this is not related to this issue) - should it be possible also to install on Windows VMs using 'make' from something like Cygwin?

Thanks!

**Comment by f-krull** [comment]
Hei, I tried to reproduce the error, but the installation seems to work for me.
Could it be that the directory was not empty and  there was already an existing file called "custom"? 

![Selection_004](https://user-images.githubusercontent.com/11461352/185909018-22199d6d-b518-4fb7-8d75-576c2faba27d.png)

**Comment by lauriejh** [comment]
That's right - I just figured it out myself 30 seconds ago! There is a "custom" symbolic link already in the folder, so mkdir -p wasn't creating the directory custom/. I removed it and the install works! Not sure whether it's necessary to replace it? 
Strange that the error didn't occur for you - I cloned the repo directly and that symbolic link is there in opt/gitea

**Comment by f-krull** [comment]
great it's solved :) 

about cygwin, honestly I'd be very surprised if it works. On the other hand I'm not very familiar with cygwin

**Comment by lauriejh** [comment]
OK I spoke a bit too soon: on running bin/update I get 

![image](https://user-images.githubusercontent.com/36158703/185910644-395aa1dd-5301-4805-b959-6c5aceb2cf78.png)

This seems like the same kind of issue, since there exists a symbolic link for 'services' which has presumably blocked that directory from being made somewhere previously...

**Comment by f-krull** [comment]
Hmm, that's weird. Have you followed the readme? Especially, running `make` (no arguments) after coping to TSD? That should have created everything

**Comment by f-krull** [comment]
closing - please let me know in case the issue still exists.
