### ISSUE TITLE
generate TULS cards based on json

### ISSUE THREAD

**Issue by drmowinckels** [LCBC-UiO/tuls#6]
So, we are slowly getting quite a lot of cards on our tuls main page. Which is great, but updating the index file is somewhat tedious and can easily break with missing out a single div or other html end tag. The index file also gets quite hard to navigate as it increases in size.

So, a suggestion from me would be to generate the cards based on a json in stead, and let users edit the json rather than the index file. And then have some js stuff generate the cards. 

json could include something like:

```json
{
    "title": "A new card",
    "description": "Card information slot. can include <a href='a/link.html'>html tags too</a>",
    "image": "/path/to/image.png",
    "url": "some/url/to/link/to.html",
    "css": "extra possible style css, optional" ,
    "index": 999 \\ for sorting, maybe? else, just generate based on the order in the file.
}
```

**Comment by f-krull** [comment]
All webpages are part of the config that can be customized for each installation. 

You a running a LCBC version of the `index-html`. Back then you had a repository called "tuls_config_p23"(?). I'd suggest to create the issue there.

**Comment by f-krull** [comment]
`tsd_tuls_cfg_p23` should be the name of your private repo

**Comment by f-krull** [comment]
@drmowinckels we have created something very similar at p22 a while ago. Maybe this is useful?

https://gist.github.com/f-krull/be4092c333da805e3c830a7d998c6bc5

**Comment by drmowinckels** [comment]
sorry, I let the url get autocompleted and didnt notice I went to your repo. Thanks for the gist! Thats about something I was looking for

**Comment by f-krull** [comment]
I transferred ownership of this repo after your issue this morning, because it seems that I'm the only maintainer. I hope that's ok with you.
The URL https://github.com/LCBC-UiO/tuls still works with a redirect
